### ISSUE TITLE
#6 - Create the Profile Page

### ISSUE THREAD

**Issue by RashedRifat** [agiledev-students-fall2022/final-project-team-stranger#11]
## Estimation of work
- Medium

Related to User Story #6 

- [ ] Create the Profile Page according to the wireframe 
- [ ] Link the Profile Page to other pages, according to the wireframe 
- [ ] Use sample images from the Picsum API to display Profile Page 
- [ ] Display sample data from a mocking API
- [ ] Allow for edit functionality.

**Comment by RichardYCX** [comment]
waiting for side bar component to get approved first

**Comment by L-Gu7** [comment]
#50 Profile combined with sidebar component
