### ISSUE TITLE
#7 -  Create the Settings Page

### ISSUE THREAD

**Issue by RashedRifat** [agiledev-students-fall2022/final-project-team-stranger#12]
## Estimation of work
- Medium

Related to User Story #7 

- [x] Create the Profile Page according to the wireframe
- [x] Link the Profile Page to other pages, according to the wireframe
- [ ] Use sample images from the Picsum API to display Profile Page
- [ ] Display sample data from a mocking API
- [x] Allow for edit functionality

**Comment by RichardYCX** [comment]
@RashedRifat why is this issue the same as #11
